# Generated by Django 5.2.4 on 2025-08-21 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0009_addsip'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaiseIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=20)),
                ('estimated_resolution_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='issue_images/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dashboard.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='VacateNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flat_no', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacate_notice', to='dashboard.tenant')),
            ],
        ),
    ]
