# Generated by Django 5.2.4 on 2025-08-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_vacatenotice_rejection_reason_vacatenotice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseissue',
            name='owner_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged'), ('Resolved by Owner', 'Resolved by Owner')], default='Pending', max_length=30),
        ),
    ]
