# Generated by Django 5.2.4 on 2025-08-29 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_raiseissue_owner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacatenotice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
