# Generated by Django 5.2.4 on 2025-08-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
