# Generated by Django 5.2.4 on 2025-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='aadhar_number',
            field=models.CharField(default='0000-0000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='aadhar_photo',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_photos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
