# Generated by Django 5.2.4 on 2025-08-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tenant_aadhar_number_tenant_aadhar_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
