# Generated by Django 5.2.4 on 2025-08-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_tenant_aadhar_number_alter_tenant_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='aadhar_number',
            field=models.CharField(default='0000-0000-0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='aadhar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_photos/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.TextField(default='Not Available'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
