# Generated by Django 5.2.4 on 2025-08-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tenant_aadhar_number_alter_tenant_aadhar_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='password',
            field=models.CharField(default='None', max_length=128),
            preserve_default=False,
        ),
    ]
