# Generated by Django 5.2.4 on 2025-08-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tenant_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='payment_type',
        ),
    ]
