# Generated by Django 5.2.4 on 2025-08-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_addstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstock',
            old_name='price_per_unit',
            new_name='buy_price',
        ),
        migrations.RemoveField(
            model_name='addstock',
            name='Total_price',
        ),
        migrations.RemoveField(
            model_name='addstock',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='addstock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
